---
title: "Problem2"
author: "Beicheng Huang"
date: "2023-11-02"
output: html_document
---

#Problem 2
```{r setup, include=FALSE}

library(tidyverse)
library(plotly)
library(p8105.datasets)
library(flexdashboard)

knitr::opts_chunk$set(
  echo = TRUE,
	warning = FALSE)
```



```{r import and clean}
noaa <- ny_noaa |>
  janitor::clean_names() |>
    mutate(
    date = as.Date(date),
    year = lubridate::year(date),
    month = lubridate::month(date),
    prcp = prcp / 10,  # Convert precipitation to mm
    tempmax = as.numeric(tmax),  # Convert character temperature to numeric degrees C 
    tempmin = as.numeric(tmin),
    tempmax = tempmax / 10,
    tempmin = tempmin / 10)

```


```{r }
temp_plot <- noaa |>
  filter(year == 1989) |>
  group_by(month) |>
  summarise(avg_tmax = mean(tempmax), avg_tmin = mean(tempmin)) |>
   plot_ly(x = ~year, 
          color = ~year,
          type = "scatter", 
          mode = "lines+markers", 
          marker = list(size = 7),
          line = list(width = 2)) |>
  add_lines(y = ~avg_tmax, name = "Average Max Temp") |>
  add_lines(y = ~avg_tmin, name = "Average Min Temp") |>
  layout(
    title = "Average Maximum and Minimum Temperatures Over Time",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Temperature (°C)")
  )

```

```{r Scatterplot}
noaa |>
  filter(!is.na(snow),year == 2008) |>
  group_by(month) |>
  summarise(avg_snow = mean(snow)) |>
  plot_ly(x = ~month, y = ~avg_snow) |>
  add_lines() |>
  layout(
    title = "Snowfall Distribution by Month in 2008",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Snowfall (mm)")
  )
```


```{r Boxplot}
noaa |>
  filter(!is.na(snwd),year == 2000) |>
  group_by(month) |>
  plot_ly(x = ~month, y = ~snwd) |>
  add_boxplot() |>
  layout(
    title = "Snow Depth Distribution by Month in 2000",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Snow Depth (mm)")
  )
```


```{r }
scatter_ggplot = 
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```

```{r flexdashboard analysis}
dashboard <- flexdashboard::flex_dashboard(
  title = "New York National Climatic Data Center Weather Data Analysis",
  tabset_panel(
    tabPanel("Scatterplot", plotlyOutput("scatter_plot")),
    tabPanel("Temperature Trends", plotlyOutput("temp_plot")),
    tabPanel("Snow Depth Distribution", plotlyOutput("box_plot"))
  )
)
```